name: Go

on:
  push:
    tags:
      - '*'

jobs:

 LINUX_24_04:
  name: Linux 24.04
  runs-on: ubuntu-24.04
  steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
          go-version: 1.24.0
    - name: Build
      run: |
        go build .
        chmod +x redirect-alias
        zip redirect-alias.zip redirect-alias redirects.json
        pwd
        ls -l *
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          /home/runner/redirect-alias/redirect-alias/redirect-alias.zip